version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs_app
    ports:
      - "3000:3000" # 호스트 포트:컨테이너 포트
    volumes:
      - .:/usr/src/app # 로컬 소스 코드와 컨테이너 동기화 (개발 시 유용)
      - /usr/src/app/node_modules # node_modules는 동기화에서 제외 (OS 호환성 문제 방지)
    depends_on:
      - mongo
    environment:
      NODE_ENV: development # 또는 production
      MONGO_URI: mongodb://mongo:27017/mydatabase # MongoDB 연결 URI
      JWT_SECRET: yourSecretKeyForJwt # JWT 시크릿 키 (실제 사용 시 변경 필요)
      JWT_ACCESS_TOKEN_EXPIRATION_TIME: 3600s # 액세스 토큰 만료 시간 (예: 1시간)
      JWT_REFRESH_TOKEN_EXPIRATION_TIME: 604800s # 리프레시 토큰 만료 시간 (예: 7일)
    restart: unless-stopped

  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db # 데이터베이스 파일 영속성을 위한 볼륨
    restart: unless-stopped

volumes:
  mongo_data: # Docker 볼륨 정의
